version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        restart: always

    web:
        build: 
            context: ./GeoServer
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        depends_on:
            - db
        restart: always

    tk103:
        build:
            context: ./Tk103Gate
            dockerfile: Dockerfile
        ports:
            - "8888:8888"
        depends_on:
            - db
        restart: always


